apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: cltpython
  name: cltpython
spec:
  ports:
  - name: 8090-8090
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: cltpython
  type: ClusterIP
status:
  loadBalancer: {}
