apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: python
  name: python
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: python
  type: NodePort
status:
  loadBalancer: {}
