apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: hazelcast
    env: prod
  name: hazelcast
spec:
  containers:
  - env:
    - name: DNS_DOMAIN
      value: cluster
    image: hazelcast/hazelcast
    name: hazelcast
    ports:
    - containerPort: 5701
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
