apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp-pod
    type: front-end
spec:
  containers:
  - name: myapp
    image: nginx
  - apiVersion: v1
  kind: Namespace
  metadata:
    name:  name
