apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: python
  name: python
spec:
  containers:
  - image: python 
    name: python
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
